nome=input("Digite um funcionario")
empresa=input("Digite a instituição")
qtdFuncionarios=int(input("Digite a qtd de funcionarios: "))
mediaMensalidade=float(input("digite a media da mensalidade"))
print(nome+ " trabalha na empresa: " + empresa)
print("possui: ", qtdFuncionarios ," Funcionarios")
print("A media da mensalidade é de: ", (mediaMensalidade))
print("=======================verifique os tipos de dados abaixo")
print("O tipo de dado da variavel [nome] ",type(nome))
print("O tipo de dado da variavel [empresa] ", type(empresa))
print("O tipo de dado da variavel [qtdFuncionarios] ", type(qtdFuncionarios))
print("O tipo de dado da variavel [mediaMensalidade] ", type(mediaMensalidade))
